/**
 * Status text for service responses
 *
 * @enum StatusTextEnum
 * @since 1.0.2
 */
/**
 * Enumeration representing the status texts for HTTP responses.
 */
/**
 * Enumeration representing the status texts for all HTTP responses.
 *
 * @enum StatusTextEnum
 * @since 1.0.2
 */
export enum StatusTextEnum {
  CONTINUE = "CONTINUE",
  SWITCHING_PROTOCOLS = "SWITCHING PROTOCOLS",
  PROCESSING = "PROCESSING",
  EARLY_HINTS = "EARLY HINTS",
  OK = "OK",
  CREATED = "CREATED SUCCESSFUL",
  ACCEPTED = "ACCEPTED",
  NON_AUTHORITATIVE_INFORMATION = "NON AUTHORITATIVE INFORMATION",
  NO_CONTENT = "NO CONTENT",
  RESET_CONTENT = "RESET CONTENT",
  PARTIAL_CONTENT = "PARTIAL CONTENT",
  MULTI_STATUS = "MULTI STATUS",
  ALREADY_REPORTED = "ALREADY REPORTED",
  IM_USED = "IM USED",
  MULTIPLE_CHOICES = "MULTIPLE CHOICES",
  MOVED_PERMANENTLY = "MOVED PERMANENTLY",
  FOUND = "FOUND",
  SEE_OTHER = "SEE OTHER",
  NOT_MODIFIED = "NOT MODIFIED",
  USE_PROXY = "USE PROXY",
  TEMPORARY_REDIRECT = "TEMPORARY REDIRECT",
  PERMANENT_REDIRECT = "PERMANENT REDIRECT",
  BAD_REQUEST = "BAD REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  PAYMENT_REQUIRED = "PAYMENT REQUIRED",
  FORBIDDEN = "NO AUTHORIZATION",
  NOT_FOUND = "NOT FOUND",
  METHOD_NOT_ALLOWED = "METHOD NOT ALLOWED",
  NOT_ACCEPTABLE = "NOT ACCEPTABLE",
  PROXY_AUTHENTICATION_REQUIRED = "PROXY AUTHENTICATION REQUIRED",
  REQUEST_TIMEOUT = "REQUEST TIMEOUT",
  CONFLICT = "CONFLICT",
  GONE = "GONE",
  LENGTH_REQUIRED = "LENGTH REQUIRED",
  PRECONDITION_FAILED = "PRECONDITION FAILED",
  PAYLOAD_TOO_LARGE = "PAYLOAD TOO LARGE",
  URI_TOO_LONG = "URI TOO LONG",
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED MEDIA TYPE",
  RANGE_NOT_SATISFIABLE = "RANGE NOT SATISFIABLE",
  EXPECTATION_FAILED = "EXPECTATION FAILED",
  IM_A_TEAPOT = "I'M A TEAPOT",
  MISDIRECTED_REQUEST = "MISDIRECTED REQUEST",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE ENTITY",
  LOCKED = "LOCKED",
  FAILED_DEPENDENCY = "FAILED DEPENDENCY",
  TOO_EARLY = "TOO EARLY",
  UPGRADE_REQUIRED = "UPGRADE REQUIRED",
  PRECONDITION_REQUIRED = "PRECONDITION REQUIRED",
  TOO_MANY_REQUESTS = "TOO MANY REQUESTS",
  REQUEST_HEADER_FIELDS_TOO_LARGE = "REQUEST HEADER FIELDS TOO LARGE",
  UNAVAILABLE_FOR_LEGAL_REASONS = "UNAVAILABLE FOR LEGAL REASONS",
  INTERNAL = "INTERNAL SERVER ERROR",
  NOT_IMPLEMENTED = "NOT IMPLEMENTED",
  BAD_GATEWAY = "BAD GATEWAY",
  SERVICE_UNAVAILABLE = "SERVICE UNAVAILABLE",
  GATEWAY_TIMEOUT = "GATEWAY TIMEOUT",
  HTTP_VERSION_NOT_SUPPORTED = "HTTP VERSION NOT SUPPORTED",
  VARIANT_ALSO_NEGOTIATES = "VARIANT ALSO NEGOTIATES",
  INSUFFICIENT_STORAGE = "INSUFFICIENT STORAGE",
  LOOP_DETECTED = "LOOP DETECTED",
  NOT_EXTENDED = "NOT EXTENDED",
  NETWORK_AUTHENTICATION_REQUIRED = "NETWORK AUTHENTICATION REQUIRED",
}
